### ISSUE TITLE
[nodejs] support local src mounting with subpaths

### ISSUE THREAD

**Issue by moritzraho** [adobe/wskdebug#23]
## Current behaviour
`> wskdebug myaction path/to/myaction/myaction.js`
=> will mount `path/to/myaction/` to `/code` in the docker container

see https://github.com/adobe/wskdebug/blob/master/src/kinds/nodejs/nodejs.js#L38

## Nice to have
would be great to have something like 
`> wskdebug myaction path/to/myaction/myaction.js --local-root path/`

## Why
this would enable things like `require('../whatever.js')` or having `node_modules` in a parent directories

**Comment by alexkli** [comment]
To avoid adding more cli args, what about using the current working directory as source mount?

I think one usually starts `wskdebug` it in the root of the „project“, the sourcePath is then always relative to it and VS Code / IDE debug launcher configurations will also usually be run in the root of the project.

AFAIK there is nothing else at this point depending on the current working directory.

**Comment by moritzraho** [comment]
Ok so you mean `sourceDir` becomes `cwd` instead of parent folder? 
I am ok with that but I think it is a breaking change

**Comment by alexkli** [comment]
Not sure if it‘s a breaking change. If the source argument is a relative path, the only change is that we mount at a higher level of the folder hierarchy and include „more“, which is what we want. It will still load the same source file.

Some examples for the mounting:

- `wskdebug myaction action.js`
   - dir: `.`
   - file: `./action.js`
   - identical
- `wskdebug myaction src/folder/action.js`
   - before
       - dir: `src/folder`
       - file: `action.js`
   - after
       - dir: `.`
       - file: `src/folder/action.js`

I think for the file watching it should also be ok. Need to try.

**Comment by moritzraho** [comment]
@alexkli the breaking change I experienced was with the vscode launch.json config and `localRoot/remoteRoot` fields, where vscode maps a remote file in `$remoteRoot/path/to/file` to a local file in `$localRoot/path/to/file`

let's say we have:
cwd -> actions -> myaction -> index.js

if localDir is mounting at parent path then `localRoot`must be set to to `cwd/actions/myactions`
if localDir is mounting at cwd then `localRoot` must be set to `cwd`

so an existing vscode config with nested subfolders will break with this change

**Comment by alexkli** [comment]
AFAICS that would also be the case with your PR, as we change the mount location after all.

wskdebug itself still works, it just affects the vscode configs and only if you have a nested path. Which probably didn’t work well... so this change would be welcome, I think. We can log a note about this change if wskdebug is called with a relative path.

In my personal experience (which might be skewed), 90% the action source file is in the root and there is no relative path.

**Comment by alexkli** [comment]
BTW we also have to think what to do with `—build-path`, it needs the same fix. Here it might need to have a separate argument, as it must be a different folder than the project = current working directory.

**Comment by moritzraho** [comment]
> AFAICS that would also be the case with your PR, as we change the mount location after all.
> 
> wskdebug itself still works, it just affects the vscode configs and only if you have a nested path. Which probably didn’t work well... so this change would be welcome, I think. We can log a note about this change if wskdebug is called with a relative path.
> 
> In my personal experience (which might be skewed), 90% the action source file is in the root and there is no relative path.

Well with my PR the default behaviour of parent mounting would be preserved and only if the `source-root` option is provided we would do the cwd mounting.

Anyways I agree with you that cwd mounting is welcome, and I am happy to do the change

**Comment by moritzraho** [comment]
> BTW we also have to think what to do with `—build-path`, it needs the same fix, in case the built source structure is nested. Here it might need to have a separate argument, as it must be a different folder than the project = current working directory.

ok good point! will push some changes together with cwd changes

**Comment by moritzraho** [comment]
@alexkli wdyt about:
`--build-path` only => mount cwd
`--build-path` and `--build-path-root` => mount build path root

**Comment by alexkli** [comment]
For only `—build-path`, I don‘t think we can ever mount cwd. It would mess up things. The build path means you compiled, transpiled etc. the entire source code into a new directory, which needs to be „isolated“ from the normal sources, i.e. it would almost always be a subdirectory.

And usually the built structure would be pretty flat, so in most cases that would work and you would only need the one `—build-path` argument.

I would keep `—build-path` as is (use parent dir). But if `—build-path-root` is given, use that for mounting, as you write.

**Comment by moritzraho** [comment]
yup makes sense thanks for the details!
